unit uConst;

interface

const
  REGSTR_PATH_ENVIRONMENTSVARIANT='HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment';

  REGST_JAVA_HOME='JAVA_HOME';
  REGST_CLASS_PATH='CLASSPATH';
  
  sRoot = 'HKEY_CLASSES_ROOT';
  sROOT_User = 'HKEY_CURRENT_USER';
  sROOT_MACHINE ='HKEY_LOCAL_MACHINE';
  sROOT_USERS ='HKEY_USERS';
  sROOT_CONFIG='HKEY_CURRENT_CONFIG';

  CATALINA_HOME='CATALINA_HOME';
  CATALINA_BASE='CATALINA_BASE';
  MAVEN_HOME ='MAVEN_HOME';

implementation

end.
